// automatically generated by the FlatBuffers compiler, do not modify

package com.bushpath.nfennel.flatbuffers;

public final class MessageType {
  private MessageType() { }
  public static final short Data = 0;
  public static final short Failure = 1;
  public static final short Query = 2;
  public static final short Write = 3;

  public static final String[] names = { "Data", "Failure", "Query", "Write", };

  public static String name(int e) { return names[e]; }
}

