// automatically generated by the FlatBuffers compiler, do not modify

package com.bushpath.nfennel.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class QueryRequest extends Table {
  public static QueryRequest getRootAsQueryRequest(ByteBuffer _bb) { return getRootAsQueryRequest(_bb, new QueryRequest()); }
  public static QueryRequest getRootAsQueryRequest(ByteBuffer _bb, QueryRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public QueryRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte query(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int queryLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer queryAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer queryInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int bufferSize() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createQueryRequest(FlatBufferBuilder builder,
      int queryOffset,
      int bufferSize) {
    builder.startObject(2);
    QueryRequest.addBufferSize(builder, bufferSize);
    QueryRequest.addQuery(builder, queryOffset);
    return QueryRequest.endQueryRequest(builder);
  }

  public static void startQueryRequest(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addQuery(FlatBufferBuilder builder, int queryOffset) { builder.addOffset(0, queryOffset, 0); }
  public static int createQueryVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startQueryVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addBufferSize(FlatBufferBuilder builder, int bufferSize) { builder.addInt(1, bufferSize, 0); }
  public static int endQueryRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

