// automatically generated by the FlatBuffers compiler, do not modify

package com.bushpath.nfennel.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class WriterCloseResponse extends Table {
  public static WriterCloseResponse getRootAsWriterCloseResponse(ByteBuffer _bb) { return getRootAsWriterCloseResponse(_bb, new WriterCloseResponse()); }
  public static WriterCloseResponse getRootAsWriterCloseResponse(ByteBuffer _bb, WriterCloseResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public WriterCloseResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startWriterCloseResponse(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endWriterCloseResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

