// automatically generated by the FlatBuffers compiler, do not modify

package com.bushpath.nfennel.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class WriterOpenResponse extends Table {
  public static WriterOpenResponse getRootAsWriterOpenResponse(ByteBuffer _bb) { return getRootAsWriterOpenResponse(_bb, new WriterOpenResponse()); }
  public static WriterOpenResponse getRootAsWriterOpenResponse(ByteBuffer _bb, WriterOpenResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public WriterOpenResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startWriterOpenResponse(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endWriterOpenResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

