// automatically generated by the FlatBuffers compiler, do not modify

package com.bushpath.nfennel.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class WriterCloseRequest extends Table {
  public static WriterCloseRequest getRootAsWriterCloseRequest(ByteBuffer _bb) { return getRootAsWriterCloseRequest(_bb, new WriterCloseRequest()); }
  public static WriterCloseRequest getRootAsWriterCloseRequest(ByteBuffer _bb, WriterCloseRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public WriterCloseRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String filename() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer filenameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer filenameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createWriterCloseRequest(FlatBufferBuilder builder,
      int filenameOffset) {
    builder.startObject(1);
    WriterCloseRequest.addFilename(builder, filenameOffset);
    return WriterCloseRequest.endWriterCloseRequest(builder);
  }

  public static void startWriterCloseRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addFilename(FlatBufferBuilder builder, int filenameOffset) { builder.addOffset(0, filenameOffset, 0); }
  public static int endWriterCloseRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

